import Head from "next/head";
import styles from "./layout.module.css";
import Header from "./header";
import Footer from "./footer";

export default function Layout({ children }) {
  return (
    <>
    <Header />
      <Head>
        <title>Regenerativo Comunicación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
      <Footer />
    </>
  );
}
